// Generated by CoffeeScript 1.12.6
var fs, irc, main;

irc = require("./irc.js");

fs = require("fs");

main = function() {
  var bot, commandFiles;
  commandFiles = fs.readdirSync("commands").filter(function(fn) {
    return fn.endsWith(".js");
  }).map(function(fn) {
    return "./commands/" + fn;
  });
  bot = irc.IRCBot.parseConfig(JSON.parse(fs.readFileSync((process.argv.length > 2 ? process.argv[2] : "config.json"))), commandFiles);
  return bot.start();
};

if (require.main === module) {
  main();
}
