// Generated by CoffeeScript 1.12.6
var cmd_users, irc,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

irc = require("../irc.js");

cmd_users = ["host:unaffiliated/gustavo6046", "ident:~Gustavo604", "ident:Gustavo604", "host:www.terrenodefogo.blogspot.com"];

module.exports = [
  {
    name: "cmd",
    perform: function(msg, custom, conn) {
      var ref, ref1;
      if ((ref = "host:" + msg.data.privmsg.hostname, indexOf.call(cmd_users, ref) < 0) && (ref1 = "ident:" + msg.data.privmsg.ident, indexOf.call(cmd_users, ref1) < 0)) {
        return msg.reply("[ EPERM ]");
      } else {
        conn.send(custom[0]);
        return msg.reply("Command sent.");
      }
    },
    matcher: new irc.PrefixedMatcher("cmd (.+)")
  }
];
