// Generated by CoffeeScript 1.12.6
var irc;

irc = require("../irc.js");

module.exports = [
  {
    name: "RELOAD",
    matcher: new irc.PrefixedMatcher("reload( (.*))?"),
    perform: function(msg, custom, conn) {
      if ((custom[1] != null) && custom[1]) {
        conn.bot.reloadCommandsFolder(custom[1]);
      } else {
        conn.bot.reloadCommands();
      }
      return msg.reply("Commands reloaded successfully.");
    }
  }
];
