// Generated by CoffeeScript 1.12.6
var irc;

irc = require("../irc.js");

module.exports = [
  {
    name: "cmdlist",
    matcher: new irc.PrefixedMatcher("(list|help)"),
    perform: function(msg, custom, conn) {
      return msg.reply("Commands available: " + (conn.bot.cmdNames.join(', ')) + ". Use the 'syntax' command to learn how to invoke them!");
    }
  }, {
    name: "cmdsyntax",
    matcher: new irc.PrefixedMatcher("syntax (.+)"),
    perform: function(msg, custom, conn) {
      var c, i, len, ref;
      ref = conn.bot.commands;
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        if (c.name.toUpperCase() === custom[0].toUpperCase()) {
          msg.reply("Regex syntax for " + custom[0] + ": '" + c.matcher.regexStr + "' | Matcher type: " + c.matcher.constructor.name);
          return;
        }
      }
      return msg.reply("No such command!");
    }
  }, {
    name: "flushq",
    matcher: new irc.PrefixedMatcher("flushq$"),
    perform: function(msg, custom, conn) {
      conn.queue = [];
      return msg.reply(".");
    }
  }
];
