// Generated by CoffeeScript 1.12.6
var irc, ping;

irc = require("../irc.js");

ping = function(msg, custom, conn) {
  if (custom[0] === "") {
    return msg.reply("PONG!");
  } else {
    return conn.send("PRIVMSG " + msg.data.privmsg.channel + " :PONG! @ " + custom[1]);
  }
};

module.exports = [
  {
    name: "status",
    perform: ping,
    matcher: new irc.PrefixedMatcher("ping( (.*))?")
  }
];
