// Generated by CoffeeScript 1.12.6
var irc, ping;

irc = require("../irc.js");

ping = function(msg, custom, conn) {
  if (custom[1] === "" || (custom[0] == null)) {
    return msg.reply("PONG!");
  } else {
    return msg.reply("PONG! @ " + custom[1]);
  }
};

module.exports = [
  {
    name: "status",
    perform: ping,
    matcher: new irc.PrefixedMatcher("ping( (.*))?")
  }
];
