// Generated by CoffeeScript 1.12.6
var irc, smw,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

irc = require("../irc.js");

smw = require("../etc/smw3.js");

module.exports = [
  {
    name: "smw3.host",
    matcher: new irc.PrefixedMatcher("smw3 host (.+)"),
    perform: function(msg, custom, conn) {
      if (smw.gametypeOf(custom[0]) == null) {
        return msg.reply("Game can't be hosted; unexistant gametype!");
      } else if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) != null) {
        return msg.reply("Game can't be hosted; there is already an SMWGame on this channel!");
      } else {
        new smw.SMWGame(conn, msg.data.privmsg.channel, new smw.gametypeOf(custom[0]), msg.reply);
        return msg.reply("Game hosted succesfully!");
      }
    }
  }, {
    name: "smw3.stop",
    matcher: new irc.PrefixedMatcher("smw3 stop$"),
    perform: function(msg, custom, conn) {
      if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) == null) {
        return msg.reply("No game running already!");
      } else {
        smw.SMWGame.findGame(conn, msg.data.privmsg.channel).stopGame();
        return msg.reply("Game stopped succesfully!!");
      }
    }
  }, {
    name: "smw3.join",
    matcher: new irc.PrefixedMatcher("smw3 join$"),
    perform: function(msg, custom, conn) {
      if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) == null) {
        return msg.reply("No game running!");
      } else {
        smw.SMWGame.findGame(conn, msg.data.privmsg.channel).addPlayer(msg.data.privmsg.nickname);
        return msg.reply("User " + msg.data.privmsg.nickname + " joined succesfully!");
      }
    }
  }, {
    name: "smw3.leave",
    matcher: new irc.PrefixedMatcher("smw3 leave$"),
    perform: function(msg, custom, conn) {
      if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) == null) {
        return msg.reply("No game running!");
      } else if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname) == null) {
        return msg.reply("You are not joined yet!");
      } else {
        return smw.SMWGame.findGame(conn, msg.data.privmsg.channel).killPlayer(msg.data.privmsg.nickname);
      }
    }
  }, {
    name: "smw3.buyWeapon",
    matcher: new irc.PrefixedMatcher("smw3 buygun (.+)"),
    perform: function(msg, custom, conn) {
      if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) == null) {
        return msg.reply("No game running!");
      } else if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname) == null) {
        return msg.reply("You are not joined yet!");
      } else {
        if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).gametype.allWeapons[custom[0]] == null) {
          return msg.reply("No such weapon!");
        } else if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).gametype.allWeapons[custom[0]].cost < smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname).attributes.money) {
          return msg.reply("Weapon too costly (" + (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname)) + "/" + (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).gametype.allWeapons[custom[0]].cost) + ")!");
        } else {
          smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname).attributes.weapons[custom[0]] = new (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).gametype.allWeapons[custom[0]])(smw.SMWGame.findGame(conn, msg.data.privmsg.channel), smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nick));
          smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname).attributes.money -= smw.SMWGame.findGame(conn, msg.data.privmsg.channel).gametype.allWeapons[custom[0]].cost;
          return msg.reply("Weapon bought successfully!");
        }
      }
    }
  }, {
    name: "smw3.shoot",
    matcher: new irc.PrefixedMatcher("smw3 shoot (.+) with (.+)"),
    perform: function(msg, custom, conn) {
      var game, targ, user, weap;
      if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) == null) {
        return msg.reply("No game running!");
      } else if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname) == null) {
        return msg.reply("You are not joined yet!");
      } else {
        targ = custom[0];
        weap = custom[1];
        game = smw.SMWGame.findGame(conn, msg.data.privmsg.channel);
        user = game.getPlayer(msg.data.privmsg.nickname);
        if (indexOf.call(user.attributes.weaopns != null, weap) < 0) {
          return msg.reply("No, you don't have that weapon!");
        } else {
          return user.attributes.weapons[weap].shoot(game.getPlayer(targ));
        }
      }
    }
  }, {
    name: "smw3.altshoot",
    matcher: new irc.PrefixedMatcher("smw3 altshoot (.+) with (.+)"),
    perform: function(msg, custom, conn) {
      var game, targ, user, weap;
      if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel) == null) {
        return msg.reply("No game running!");
      } else if (smw.SMWGame.findGame(conn, msg.data.privmsg.channel).getPlayer(msg.data.privmsg.nickname) == null) {
        return msg.reply("You are not joined yet!");
      } else {
        targ = custom[0];
        weap = custom[1];
        game = smw.SMWGame.findGame(conn, msg.data.privmsg.channel);
        user = game.getPlayer(msg.data.privmsg.nickname);
        if (indexOf.call(user.attributes.weaopns != null, weap) < 0) {
          return msg.reply("No, you don't have that weapon!");
        } else {
          return user.attributes.weapons[weap].altShoot(game.getPlayer(targ));
        }
      }
    }
  }
];
