// Generated by CoffeeScript 1.12.6
var irc, urban;

urban = require("urban");

irc = require("../irc.js");

module.exports = [
  {
    name: "udict",
    perform: function(msg, custom, conn) {
      var query;
      if (!custom[0].startsWith(" ")) {
        return;
      }
      if (custom[1] === "") {
        query = urban.random();
      } else {
        query = urban(custom[1]);
      }
      return query.first(function(data) {
        if (data != null) {
          return msg.reply("[#" + data.defid + "] '" + data.word + "' by " + data.author + " (+" + data.thumbs_up + " -" + data.thumbs_down + "): " + (data.definition.replace("\n", "   ").slice(0, 120)) + " | e.g. " + (data.example.replace("\n", "   ").slice(0, 95)) + " - " + data.permalink);
        } else {
          return msg.reply("Definition not found.");
        }
      });
    },
    matcher: new irc.PrefixedMatcher("ud( (.*))?")
  }
];
