// Generated by CoffeeScript 1.12.6
var irc;

irc = require("../irc.js");

module.exports = [
  {
    name: "um",
    matcher: new irc.PrefixedMatcher("um (.+)"),
    perform: function(msg, custom, conn) {
      return msg.reply(custom[0].split(" ").join(", um, ") + "...");
    }
  }
];
